### ISSUE TITLE
[Backend] As a user, I can get the raw HTML of one Google search page

### ISSUE THREAD

**Issue by toby-thanathip** [nimblehq/ic-rails-huey-toby#14]
## Why

A search result must be made for one keyword in the CSV file, once the user uploads the file (Google)

## Acceptance Criteria

- Make sure we're able to scrape the raw HTML for _one_ keyword (and store it in the `html_code` field):
- Write unit and integration tests

## Design
N/A

## Resources
https://github.com/sparklemotion/nokogiri

**Comment by hoangmirs** [comment]
You might need another story to handle this => "⚠ You must find a way to work around the limitations of mass-searching keywords as Google and Bing prevents it."

**Comment by hoangnguyen92dn** [comment]
@Tuubz Regarding the workaround to bypass the limitations of mass-searching, it should belong to the task regarding background job to process searching or we should have another backlog for this.

**Comment by Tuubz** [comment]
@hoangnguyen92dn @hoangmirs 

This doesn't fit in the background job issue (#19), since we will make the actual call to Google in this issue.

Do we really need a new issue for this? Making the call to Google [should be super easy](https://github.com/sparklemotion/nokogiri#how-to-use-nokogiri)

So the biggest difficulty here is to retry and find a workaround for the mass-searching 💭 

Please let me know if I'm missing something,  🙏

**Comment by Tuubz** [comment]
✅ I've split it up into two issues:

- Get HTML from one search result (#14)
- Get HTML from multiple search results (#26)

@hoangnguyen92dn @hoangmirs Please let me know if this works for you 🙏

**Comment by hoangmirs** [comment]
I raised this because if you scrape multiple keywords, Google might block you when you exceed certain requests. I don't know the specific number, but you could miss a lot of keyword results if you have a file with 1000 keywords. The retries and timeout could not help on that case 💭
